# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulCompanyAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompanyExercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successfulcompanyattempt_set', related_query_name='successfulcompanyattempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
