# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='needed_subscription',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=15),
        ),
    ]
