# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_successfulcompanyattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successfulcompanyattempt',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
