# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171224_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='name',
            new_name='internal_name',
        ),
    ]
