# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180115_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='create_company_exercise',
        ),
        migrations.AddField(
            model_name='global',
            name='bool_value',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='global',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='global',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='global',
            name='text_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
