# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171224_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='needed_subscription',
            field=models.CharField(choices=[(None, 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[(None, 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=15),
        ),
    ]
