# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 23:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171225_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('objective', models.TextField()),
                ('working_query', models.TextField()),
                ('expected_headers', models.BinaryField()),
                ('expected_rows', models.BinaryField()),
                ('column_descriptions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'advanced')], default='novice', max_length=20)),
                ('new', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_company_exercise', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('objective', models.TextField()),
                ('working_query', models.TextField()),
                ('expected_headers', models.BinaryField()),
                ('expected_rows', models.BinaryField()),
                ('column_descriptions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('shareable', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='database',
            name='needed_subscription',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Database'),
        ),
        migrations.AddField(
            model_name='companyexercise',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Database'),
        ),
    ]
