# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180105_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexercise',
            name='needed_subscription',
            field=models.CharField(choices=[(None, 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=15),
        ),
        migrations.AddField(
            model_name='companyexercise',
            name='subject',
            field=models.CharField(choices=[('postgres', 'Postgres')], default='postgres', max_length=20),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='subject',
            field=models.CharField(choices=[('postgres', 'Postgres')], default='postgres', max_length=20),
        ),
        migrations.AlterField(
            model_name='database',
            name='needed_subscription',
            field=models.CharField(choices=[(None, 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=15),
        ),
    ]
