# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180123_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_id',
            new_name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
