# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180124_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_default_source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
