# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_stripe_default_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_current_period_end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_current_period_start',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
