# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invitee_registered',
            new_name='assigned_to_invitee',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='invitee_char',
            new_name='invitee_s',
        ),
    ]
