# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180108_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
