# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_slated_for_downgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('going_to', models.CharField(choices=[(None, 'None'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
